language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - echo 'before_script'

jobs:
  include:
    - stage: "stage 1"
      if: env(FOO) = foo
      script: echo 'script stage 1'
    - stage: "stage 2"
      if: env(FOO) = fasas
      script: echo 'script stage 2'

after_script:
  - bash ./after.sh FOO