language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - echo 'before_script'

jobs:
  include:
    - stage: "stage 1"
      script: test FOO=foo \ 
              echo 'script stage 1'
    - stage: "stage 2"
      script: test FOO=hjhjhjhj \
              echo 'script stage 2'

after_script:
  - test FOO=foo \
    echo 'after_script'